name: first workflow

env:
  WORKFLOW_VAR: "This variable is declared at the workflow level"

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "This is a job variable"
    steps:
      - name: firstJob script
        shell: bash
        run: echo Hello World! This is the first job
      - name: the checkout action
        uses: actions/checkout@v6
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}
      - name: time
        run: |
          echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
        shell: bash
        run: |
          echo this is second job
          echo and this is a multi line script
      - name: environment variables
        env:
          STEP_VAR: "This variable is declared at step level"
        run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
